### PR TITLE
fix(imports): only import matplotlib where needed and if gui is enabled

### LINKED ISSUE #786: [bug] Not all netpyne submodules respect the `netpyne.__gui__` variable, making netpyne currently unusable on hpcs
I'm trying to run the [NeuroML conversion of Human L23 model](https://github.com/sanjayankur31/Human-L2-3-Cortical-Microcircuit/tree/feat/neuroml) on NSG using NetPyNE. The generation of the NetPyNE script etc. goes correctly, the mod files are also generated and compiled fine. However, when the python script is run on NSG, it errors because matplotlib is also imported by netpyne and it cannot acquire the lock file, probably because all the N mpi processes are trying to acquire it. 

Would you folks have experience with running sims on NSG using NetPyNE? Is it necessary for NetPyNE to import matplotlib even if no analysis/plotting is to be done?

Here's a zip of the python script and mod files: [LEMS_HL23_0.01_Sim_NSG.zip](https://github.com/suny-downstate-medical-center/netpyne/files/13227823/LEMS_HL23_0.01_Sim_NSG.zip)

The complete error output from the nsg job is here: [stderr.txt](https://github.com/suny-downstate-medical-center/netpyne/files/13227827/stderr.txt)

### PR DESCRIPTION
**Pull request by sanjayankur31**
Fixes #786

Same as https://github.com/suny-downstate-medical-center/netpyne/pull/787, but cherry-picked to apply against development

### CODE REVIEW

**Comment by sanjayankur31** [comment]
A simple test script to check matplotlib imports is here (maybe this should be added as a test in CI?)

```python
"""
Example python script to run on NSGR

File: example.py

Copyright 2023 OSB contributors
"""


from netpyne import specs
from netpyne import sim
from netpyne import __version__ as version

import sys
import pkg_resources

if __name__ == "__main__":
    print("Running example script to list Python packages...")

    with open("output.txt", "w") as f:
        print(f"Python version is: {sys.version}", file=f)
        print("Installed packages on NSG:", file=f)
        dists = [str(d).replace(" ", "==") for d in pkg_resources.working_set]
        for i in dists:
            print(i, file=f)

    for k in sys.modules.keys():
        if "matplotlib" in k:
            print(f"matplotlib still loaded: {k}")

    print(f"Args are: {sys.argv}")
    if sys.argv.count("-nogui") > 0:
        print("nogui found")
    print("Done!")
```

**Review by jchen6727 — APPROVED** [review]
reviewed the netpyne/analysis, netpyne/plotting, netpyne/support
looks good, probably will receive NameError: name 'plt' is not defined now for many of the plotting functions if they are called by accident with -nogui
if @vvbragin

**Comment by vvbragin** [comment]
@sanjayankur31 @jchen6727 thank you guys, looks good to me as well. For those plotting functions highlighted by James, where `plt` is needed, I would move the import inside the functions themselves, so the importing won't get triggered unless user explicitly wants to call that func. (Conceptually, I wouldn't connect plotting functions to -nogui option, because the latter is not about plotting but specifically about GUI as far as I understand). What do you think?

Anyways, I'd merge this one PR, and the rest of modifications I would make in separate one (it's just easier for me then dealing with forked repo's PRs)

**Comment by sanjayankur31** [comment]
Hello,

Yes, moving the imports into the functions is probably the best thing to do---or if the main netpyne `__init__` imports the necessary matplotlib bits, then the other sub-modules could just use it from there, so you don't need to re-import things again and again (like the `__gui__` variable). In general, it's probably a good idea to keep the analysis bits separate from the modelling/simulation bits, unless one can only use the analysis bits if they've first created a model and run a simulation..

**Pull request merged**
