### PR TITLE
feat: unpin matplotlib

### LINKED ISSUE #692: Remove matplotlib version requirements after next matplotlib update
The latest matplotlib release has a bug when trying to copy rcParams (required for new plotting).

I changed the version requirement to <=3.5.1 in both requirements.txt and install_requires in setup.py.

After the next matplotlib release, we should test again and remove version requirement when corrected.

### PR DESCRIPTION
**Pull request by sanjayankur31**
Fixes #692

The old version of netpyne does not provide wheels for py3.11 etc.

### CODE REVIEW

**Comment by vvbragin** [comment]
hi @sanjayankur31, thanks for your help, but unfortunately the issue is still there with the newest matplotlib.. I'm on it

**Comment by sanjayankur31** [comment]
That's unfortunate. What's the issue btw? I couldn't exactly figure it out?

**Comment by vvbragin** [comment]
That's a minor thing with copying style params, but it makes the whole flow crash.. I have a workaround, will test it a bit more and push today hopefully

**Comment by vvbragin** [comment]
this change is included into root-cause fix https://github.com/suny-downstate-medical-center/netpyne/commit/d695be9aca30c0d75f6430e79712dad953afa1a7

**Pull request closed without merging**
